# generated by datamodel-codegen:
#   filename:  AvatarSkillExcelConfigData.json
#   timestamp: 2022-11-01T03:55:02+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class AvatarSkillExcelConfigDatum(BaseModel):
    id: int  # 技能Id
    nameTextMapHash: int  # 技能名称文本
    abilityName: str  # 技能名称
    descTextMapHash: int  # 技能描述文本 | 几乎是空白
    skillIcon: str  # 技能图标
    costStamina: Optional[float] = None  # 体力消耗
    maxChargeNum: int  # 可累积次数
    lockShape: str  # 索敌范围
    lockWeightParams: List[float]  # 索敌公式权重
    isAttackCameraLock: Optional[bool] = None  # 是否为默认镜头
    buffIcon: str  # 加成图标 | 只有芭芭拉有？
    globalValueKey: str  #
    cdTime: Optional[float] = None  # 冷却时长
    triggerID: Optional[int] = None  # 触发Id
    dragType: Optional[str] = None  # 是否可拖动
    showIconArrow: Optional[bool] = None  # 是否显示箭头
    proudSkillGroupId: Optional[int] = None
    forceCanDoSkill: Optional[bool] = None  # CanDoSkill为false强制可用
    costElemType: Optional[str] = None  # 元素能量消耗类型 | 七种元素e.g.胡桃大招消耗60点火元素能量
    costElemVal: Optional[float] = None  # 元素能量消耗值 | e.g.胡桃大招消耗60点 这个值为60
    ignoreCDMinusRatio: Optional[bool] = None  # 忽略cd重置效果 | e.g. 七七6命复活
    isRanged: Optional[bool] = None  # 是范围攻击
    needMonitor: Optional[str] = None  # 是否监控状态
    defaultLocked: Optional[bool] = None  # 默认锁定
    needStore: Optional[bool] = None  # 是否存档
    cdSlot: Optional[int] = None  # 处理冷却所需技能槽
    energyMin: Optional[float] = None  # 消耗能量最小值
    OMECNFGPGHM: Optional[int] = None


class AvatarSkillExcelConfigData(BaseModel):
    __root__: List[AvatarSkillExcelConfigDatum]
