# generated by datamodel-codegen:
#   filename:  AvatarCurveExcelConfigData.json
#   timestamp: 2022-11-01T03:54:59+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class CurveInfo(BaseModel):
    type: str  # 类型
    arith: str  # 运算
    value: float  # 值


class AvatarCurveExcelConfigDatum(BaseModel):
    level: int  # 角色等级
    curveInfos: List[CurveInfo]  # 属性成长详情列表


class AvatarCurveExcelConfigData(BaseModel):
    __root__: List[AvatarCurveExcelConfigDatum]
