# generated by datamodel-codegen:
#   filename:  AvatarCodexExcelConfigData.json
#   timestamp: 2022-11-01T03:54:57+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class AvatarCodexExcelConfigDatum(BaseModel):
    sortId: int  # 排序Id
    sortFactor: int  # 排序
    avatarId: int  # 角色Id
    beginTime: str  # 开放时间
    IMPOGOCCALB: Optional[bool] = None  # 未获得不展示


class AvatarCodexExcelConfigData(BaseModel):
    __root__: List[AvatarCodexExcelConfigDatum]
