# generated by datamodel-codegen:
#   filename:  AvatarCostumeExcelConfigData.json
#   timestamp: 2022-11-01T03:54:58+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class AvatarCostumeExcelConfigDatum(BaseModel):
    OGKFGGNLLDG: int
    KCLGNCODKCB: Optional[int] = None
    nameTextMapHash: int
    descTextMapHash: int
    itemId: Optional[int] = None
    AKOANLMAFDD: int
    jsonName: str
    POKBOHJOIAO: Optional[int] = None
    KBOJMHOEIGP: Optional[int] = None
    JHLHOFMIACH: Optional[int] = None
    MOBDPMDPOLK: Optional[int] = None
    CPCBAHOICOI: Optional[int] = None
    EAPJFIFAKJD: Optional[int] = None
    HLAPLALPJMA: Optional[int] = None
    PKKOEBGNGDI: Optional[int] = None
    KCGENIAAGAN: Optional[int] = None
    IFIODPDADEI: str
    sideIconName: str
    CAMHHHOEOKL: Optional[int] = None
    FNBIOFBAAOE: Optional[int] = None
    MKBIFLBNLON: Optional[bool] = None
    hide: Optional[bool] = None
    gachaCardNameHashSuffix: Optional[int] = None
    coopPicNameHashSuffix: Optional[int] = None
    IPDGIHCGHNI: Optional[int] = None
    DHPHIEMEEBB: Optional[int] = None
    HIPJFMBAEMO: Optional[int] = None
    FFJDLEKIFBF: Optional[int] = None
    isDefault: Optional[bool] = None
    ENBLJGDBMMK: Optional[bool] = None


class AvatarCostumeExcelConfigData(BaseModel):
    __root__: List[AvatarCostumeExcelConfigDatum]
