# generated by datamodel-codegen:
#   filename:  AvatarExcelConfigData.json
#   timestamp: 2022-11-01T03:54:59+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class PropGrowCurve(BaseModel):
    type: str
    growCurve: str


class AvatarExcelConfigDatum(BaseModel):
    bodyType: str  # 体型
    scriptDataPathHashSuffix: int  # Lua脚本路径后缀
    scriptDataPathHashPre: int  # Lua脚本路径前缀
    iconName: str  # 图鉴图像
    sideIconName: str  # 侧视小图
    qualityType: str  # 稀有度
    chargeEfficiency: float  # 充能速率
    combatConfigHashSuffix: int  # 战斗配置
    combatConfigHashPre: int  # 战斗配置
    initialWeapon: int  # 初始武器
    weaponType: str  # 武器类型
    manekinPathHashSuffix: int
    manekinPathHashPre: int
    imageName: str  # 图像名称
    MJGNGJHBAGI: Optional[int] = None
    gachaCardNameHashPre: Optional[int] = None
    CBFOEKCENEA: Optional[int] = None
    PAGADEAKHAC: Optional[int] = None
    cutsceneShow: str
    skillDepotId: int
    staminaRecoverSpeed: float  # 体力恢复速度
    candSkillDepotIds: List[int]
    manekinJsonConfigHashSuffix: int
    manekinJsonConfigHashPre: int
    manekinMotionConfig: int
    descTextMapHash: int  # 角色简介文本
    avatarIdentityType: Optional[str] = None  # 角色
    avatarPromoteId: int  # 角色升级Id
    avatarPromoteRewardLevelList: List[int]  # 角色突破等阶奖励列表
    avatarPromoteRewardIdList: List[int]  # 角色突破等阶奖励Id
    featureTagGroupID: int  # 特性tag
    infoDescTextMapHash: int  # 角色简介文本
    hpBase: float  # 基础生命值
    attackBase: float  # 基础攻击力
    defenseBase: float  # 基础防御力
    critical: float  # 基础暴击率
    criticalHurt: float  # 基础暴击伤害
    propGrowCurves: List[PropGrowCurve]  # 属性成长曲线列表 | 每个属性对应的成长曲线列表
    prefabPathRagdollHashSuffix: int
    prefabPathRagdollHashPre: int
    animatorConfigPathHashSuffix: int  # 动画配置路径
    NJIEKKLKLLD: int
    id: int  # 角色Id
    nameTextMapHash: int  # 角色名称文本
    prefabPathHashSuffix: int
    prefabPathHashPre: int
    prefabPathRemoteHashSuffix: int
    prefabPathRemoteHashPre: int
    controllerPathHashSuffix: int
    controllerPathHashPre: int
    controllerPathRemoteHashSuffix: int
    controllerPathRemoteHashPre: int
    LODPatternName: str
    useType: Optional[str] = None
    CEKDEENNDNB: Optional[int] = None
    gachaImageNameHashPre: Optional[int] = None  # 抽卡图像hash前缀
    isRangeAttack: Optional[bool] = None  # 具有范围攻击
    gachaImageNameHashSuffix: Optional[int] = None  # 抽卡图像hash后缀
    coopPicNameHashPre: Optional[int] = None  # 邀约任务图像hash后缀


class AvatarExcelConfigData(BaseModel):
    __root__: List[AvatarExcelConfigDatum]
