# generated by datamodel-codegen:
#   filename:  AvatarFettersLevelExcelConfigData.json
#   timestamp: 2022-11-01T03:55:00+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class AvatarFettersLevelExcelConfigDatum(BaseModel):
    fetterLevel: int  # 好感等级
    needExp: int  # 所需经验


class AvatarFettersLevelExcelConfigData(BaseModel):
    __root__: List[AvatarFettersLevelExcelConfigDatum]
