# generated by datamodel-codegen:
#   filename:  ChapterExcelConfigData.json
#   timestamp: 2022-11-01T03:55:04+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class ChapterExcelConfigDatum(BaseModel):
    id: int
    beginQuestId: Optional[int] = None
    endQuestId: Optional[int] = None
    needBeginTimeStr: str
    chapterNumTextMapHash: int
    chapterTitleTextMapHash: int
    chapterIcon: str
    chapterImageHashSuffix: Optional[int] = None
    chapterImageHashPre: Optional[int] = None
    chapterImageTitleTextMapHash: int
    chapterSerialNumberIcon: str
    needPlayerLevel: Optional[int] = None
    activityId: Optional[int] = None
    inActivityNeedPlayerLevel: Optional[int] = None


class ChapterExcelConfigData(BaseModel):
    __root__: List[ChapterExcelConfigDatum]
