# generated by datamodel-codegen:
#   filename:  CookBonusExcelConfigData.json
#   timestamp: 2022-11-01T03:55:06+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class CookBonusExcelConfigDatum(BaseModel):
    avatarId: int
    recipeId: int
    bonusType: str
    paramVec: List[int]
    complexParamVec: List[int]


class CookBonusExcelConfigData(BaseModel):
    __root__: List[CookBonusExcelConfigDatum]
