# generated by datamodel-codegen:
#   filename:  DailyTaskExcelConfigData.json
#   timestamp: 2022-11-01T03:55:08+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class DailyTaskExcelConfigDatum(BaseModel):
    ID: int
    cityId: int
    poolId: int
    type: Optional[str] = None
    rarity: Optional[int] = None
    oldGroupVec: List[int]
    newGroupVec: List[int]
    finishType: Optional[str] = None
    finishProgress: Optional[int] = None
    taskRewardId: int
    centerPosition: str
    enterDistance: int
    exitDistance: int
    titleTextMapHash: int
    descriptionTextMapHash: int
    targetTextMapHash: int
    radarRadius: Optional[float] = None
    finishParam1: Optional[int] = None
    finishParam2: Optional[int] = None
    questId: Optional[int] = None


class DailyTaskExcelConfigData(BaseModel):
    __root__: List[DailyTaskExcelConfigDatum]
