# generated by datamodel-codegen:
#   filename:  DailyDungeonConfigData.json
#   timestamp: 2022-11-01T03:55:07+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class DailyDungeonConfigDatum(BaseModel):
    id: int
    monday: List[int]
    tuesday: List[int]
    wednesday: List[int]
    thursday: List[int]
    friday: List[int]
    saturday: List[int]
    sunday: List[int]


class DailyDungeonConfigData(BaseModel):
    __root__: List[DailyDungeonConfigDatum]
