# generated by datamodel-codegen:
#   filename:  DailyTaskLevelExcelConfigData.json
#   timestamp: 2022-11-01T03:55:08+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class DailyTaskLevelExcelConfigDatum(BaseModel):
    ID: int
    minPlayerLevel: int
    maxPlayerLevel: int
    scoreDropId: int
    scorePreviewRewardId: int
    groupReviseLevel: Optional[int] = None


class DailyTaskLevelExcelConfigData(BaseModel):
    __root__: List[DailyTaskLevelExcelConfigDatum]
