# generated by datamodel-codegen:
#   filename:  DailyTaskRewardExcelConfigData.json
#   timestamp: 2022-11-01T03:55:09+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class DropVecItem(BaseModel):
    dropId: int
    previewRewardId: int


class DailyTaskRewardExcelConfigDatum(BaseModel):
    ID: int
    dropVec: List[DropVecItem]


class DailyTaskRewardExcelConfigData(BaseModel):
    __root__: List[DailyTaskRewardExcelConfigDatum]
