# generated by datamodel-codegen:
#   filename:  DialogExcelConfigData.json
#   timestamp: 2022-11-01T03:55:57+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class TalkRole(BaseModel):
    _type: Optional[str] = None
    _id: str


class DialogExcelConfigDatum(BaseModel):
    id: int
    nextDialogs: List[int]
    talkRole: TalkRole
    talkContentTextMapHash: int
    talkTitleTextMapHash: int
    talkRoleNameTextMapHash: int
    talkAssetPath: str
    talkAssetPathAlter: str
    talkAudioName: str
    actionBefore: str
    actionWhile: str
    actionAfter: str
    optionIcon: str
    talkShowType: Optional[str] = None
    groupId: Optional[int] = None
    showDuration: Optional[float] = None


class DialogExcelConfigData(BaseModel):
    __root__: List[DialogExcelConfigDatum]
