# generated by datamodel-codegen:
#   filename:  DieTypeTipsExcelConfigData.json
#   timestamp: 2022-11-01T03:55:58+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class DieTypeTipsExcelConfigDatum(BaseModel):
    id: int
    dieType: str
    tips: List[int]
    monsterID: Optional[int] = None


class DieTypeTipsExcelConfigData(BaseModel):
    __root__: List[DieTypeTipsExcelConfigDatum]
