# generated by datamodel-codegen:
#   filename:  DungeonChallengeConfigData.json
#   timestamp: 2022-11-01T03:55:59+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class DungeonChallengeConfigDatum(BaseModel):
    id: int
    targetTextTemplateTextMapHash: int
    subTargetTextTemplateTextMapHash: int
    progressTextTemplateTextMapHash: int
    subProgressTextTemplateTextMapHash: int
    iconPath: str
    challengeType: str
    APEHEBKDDKC: List[str]
    noSuccessHint: Optional[bool] = None
    interruptButtonType: Optional[str] = None
    noFailHint: Optional[bool] = None
    isBlockTopTimer: Optional[bool] = None
    subChallengeFadeOutRule: Optional[str] = None
    subChallengeFadeOutDelayTime: Optional[float] = None
    subChallengeBannerRule: Optional[str] = None
    AGPEPEDENCE: Optional[bool] = None
    recordType: Optional[str] = None
    HOGLJJHPPCC: Optional[bool] = None
    isSuccessWhenNotSettled: Optional[bool] = None
    activitySkillID: Optional[int] = None
    isForwardTiming: Optional[bool] = None
    NEBCEIKJCMI: Optional[bool] = None
    PNCLDNBHKDJ: Optional[str] = None
    DNFAFNMMMDP: Optional[str] = None
    ENONHOGJDDN: Optional[str] = None
    NJBJIKAIENN: Optional[str] = None


class DungeonChallengeConfigData(BaseModel):
    __root__: List[DungeonChallengeConfigDatum]
