# generated by datamodel-codegen:
#   filename:  DungeonExcelConfigData.json
#   timestamp: 2022-11-01T03:56:00+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class LevelConfigMap(BaseModel):
    field_1000: Optional[int] = Field(None, alias='1000')
    field_1001: Optional[int] = Field(None, alias='1001')
    field_1002: Optional[int] = Field(None, alias='1002')
    field_1070: Optional[int] = Field(None, alias='1070')
    field_1071: Optional[int] = Field(None, alias='1071')
    field_1050: Optional[int] = Field(None, alias='1050')
    field_1051: Optional[int] = Field(None, alias='1051')
    field_1161: Optional[int] = Field(None, alias='1161')
    field_1162: Optional[int] = Field(None, alias='1162')
    field_1163: Optional[int] = Field(None, alias='1163')
    field_1164: Optional[int] = Field(None, alias='1164')
    field_1165: Optional[int] = Field(None, alias='1165')
    field_1166: Optional[int] = Field(None, alias='1166')
    field_1052: Optional[int] = Field(None, alias='1052')
    field_1053: Optional[int] = Field(None, alias='1053')
    field_1369: Optional[int] = Field(None, alias='1369')
    field_1740: Optional[int] = Field(None, alias='1740')
    field_1741: Optional[int] = Field(None, alias='1741')
    field_1742: Optional[int] = Field(None, alias='1742')
    field_1701: Optional[int] = Field(None, alias='1701')
    field_1386: Optional[int] = Field(None, alias='1386')
    field_1619: Optional[int] = Field(None, alias='1619')
    field_1688: Optional[int] = Field(None, alias='1688')
    field_1728: Optional[int] = Field(None, alias='1728')
    field_1743: Optional[int] = Field(None, alias='1743')
    field_1744: Optional[int] = Field(None, alias='1744')
    field_1364: Optional[int] = Field(None, alias='1364')
    field_1674: Optional[int] = Field(None, alias='1674')
    field_1675: Optional[int] = Field(None, alias='1675')
    field_1676: Optional[int] = Field(None, alias='1676')
    field_1370: Optional[int] = Field(None, alias='1370')
    field_1612: Optional[int] = Field(None, alias='1612')
    field_1613: Optional[int] = Field(None, alias='1613')
    field_1614: Optional[int] = Field(None, alias='1614')
    field_1615: Optional[int] = Field(None, alias='1615')
    field_1616: Optional[int] = Field(None, alias='1616')
    field_1617: Optional[int] = Field(None, alias='1617')
    field_1632: Optional[int] = Field(None, alias='1632')
    field_1622: Optional[int] = Field(None, alias='1622')
    field_1624: Optional[int] = Field(None, alias='1624')
    field_1620: Optional[int] = Field(None, alias='1620')
    field_1621: Optional[int] = Field(None, alias='1621')
    field_1623: Optional[int] = Field(None, alias='1623')
    field_1625: Optional[int] = Field(None, alias='1625')
    field_1626: Optional[int] = Field(None, alias='1626')
    field_1639: Optional[int] = Field(None, alias='1639')
    field_1640: Optional[int] = Field(None, alias='1640')
    field_1683: Optional[int] = Field(None, alias='1683')
    field_1689: Optional[int] = Field(None, alias='1689')
    field_1690: Optional[int] = Field(None, alias='1690')
    field_1691: Optional[int] = Field(None, alias='1691')
    field_1692: Optional[int] = Field(None, alias='1692')
    field_1693: Optional[int] = Field(None, alias='1693')
    field_1694: Optional[int] = Field(None, alias='1694')
    field_1551: Optional[int] = Field(None, alias='1551')
    field_1553: Optional[int] = Field(None, alias='1553')
    field_1552: Optional[int] = Field(None, alias='1552')
    field_1554: Optional[int] = Field(None, alias='1554')
    field_1737: Optional[int] = Field(None, alias='1737')
    field_1736: Optional[int] = Field(None, alias='1736')
    field_1302: Optional[int] = Field(None, alias='1302')
    field_1303: Optional[int] = Field(None, alias='1303')
    field_1301: Optional[int] = Field(None, alias='1301')
    field_1605: Optional[int] = Field(None, alias='1605')
    field_1726: Optional[int] = Field(None, alias='1726')
    field_1604: Optional[int] = Field(None, alias='1604')
    field_1725: Optional[int] = Field(None, alias='1725')
    field_1100: Optional[int] = Field(None, alias='1100')
    field_1101: Optional[int] = Field(None, alias='1101')
    field_1102: Optional[int] = Field(None, alias='1102')
    field_1103: Optional[int] = Field(None, alias='1103')
    field_1104: Optional[int] = Field(None, alias='1104')
    field_1105: Optional[int] = Field(None, alias='1105')
    field_1106: Optional[int] = Field(None, alias='1106')
    field_1107: Optional[int] = Field(None, alias='1107')
    field_1108: Optional[int] = Field(None, alias='1108')
    field_1109: Optional[int] = Field(None, alias='1109')
    field_1110: Optional[int] = Field(None, alias='1110')
    field_1111: Optional[int] = Field(None, alias='1111')
    field_1112: Optional[int] = Field(None, alias='1112')
    field_1113: Optional[int] = Field(None, alias='1113')
    field_1377: Optional[int] = Field(None, alias='1377')
    field_1378: Optional[int] = Field(None, alias='1378')
    field_1379: Optional[int] = Field(None, alias='1379')
    field_1727: Optional[int] = Field(None, alias='1727')
    field_1114: Optional[int] = Field(None, alias='1114')
    field_1115: Optional[int] = Field(None, alias='1115')
    field_1116: Optional[int] = Field(None, alias='1116')
    field_1117: Optional[int] = Field(None, alias='1117')
    field_1118: Optional[int] = Field(None, alias='1118')
    field_1119: Optional[int] = Field(None, alias='1119')
    field_1120: Optional[int] = Field(None, alias='1120')
    field_1121: Optional[int] = Field(None, alias='1121')
    field_1122: Optional[int] = Field(None, alias='1122')
    field_1123: Optional[int] = Field(None, alias='1123')
    field_1124: Optional[int] = Field(None, alias='1124')
    field_1125: Optional[int] = Field(None, alias='1125')
    field_1126: Optional[int] = Field(None, alias='1126')
    field_1127: Optional[int] = Field(None, alias='1127')
    field_1128: Optional[int] = Field(None, alias='1128')
    field_1129: Optional[int] = Field(None, alias='1129')
    field_1344: Optional[int] = Field(None, alias='1344')
    field_1700: Optional[int] = Field(None, alias='1700')
    field_1606: Optional[int] = Field(None, alias='1606')
    field_1677: Optional[int] = Field(None, alias='1677')
    field_1304: Optional[int] = Field(None, alias='1304')
    field_1305: Optional[int] = Field(None, alias='1305')
    field_1300: Optional[int] = Field(None, alias='1300')
    field_43: Optional[int] = Field(None, alias='43')
    field_1354: Optional[int] = Field(None, alias='1354')
    field_1353: Optional[int] = Field(None, alias='1353')
    field_1355: Optional[int] = Field(None, alias='1355')
    field_1356: Optional[int] = Field(None, alias='1356')
    field_1365: Optional[int] = Field(None, alias='1365')
    field_1371: Optional[int] = Field(None, alias='1371')
    field_1372: Optional[int] = Field(None, alias='1372')
    field_1373: Optional[int] = Field(None, alias='1373')
    field_1374: Optional[int] = Field(None, alias='1374')
    field_1375: Optional[int] = Field(None, alias='1375')
    field_1376: Optional[int] = Field(None, alias='1376')
    field_1465: Optional[int] = Field(None, alias='1465')
    field_1466: Optional[int] = Field(None, alias='1466')
    field_1467: Optional[int] = Field(None, alias='1467')
    field_1461: Optional[int] = Field(None, alias='1461')
    field_1462: Optional[int] = Field(None, alias='1462')
    field_1463: Optional[int] = Field(None, alias='1463')
    field_1464: Optional[int] = Field(None, alias='1464')
    field_1671: Optional[int] = Field(None, alias='1671')
    field_1672: Optional[int] = Field(None, alias='1672')
    field_1673: Optional[int] = Field(None, alias='1673')
    field_1607: Optional[int] = Field(None, alias='1607')
    field_1633: Optional[int] = Field(None, alias='1633')
    field_1707: Optional[int] = Field(None, alias='1707')
    field_1724: Optional[int] = Field(None, alias='1724')
    field_1713: Optional[int] = Field(None, alias='1713')
    field_1720: Optional[int] = Field(None, alias='1720')
    field_1721: Optional[int] = Field(None, alias='1721')
    field_1722: Optional[int] = Field(None, alias='1722')
    field_1723: Optional[int] = Field(None, alias='1723')


class DungeonExcelConfigDatum(BaseModel):
    id: int
    nameTextMapHash: int
    displayNameTextMapHash: int
    descTextMapHash: int
    type: str
    sceneId: int
    involveType: str
    showLevel: Optional[int] = None
    limitLevel: Optional[int] = None
    levelRevise: Optional[int] = None
    passCond: Optional[int] = None
    reviveMaxCount: Optional[int] = None
    dayEnterCount: Optional[int] = None
    JNHMFILLDCE: List[Dict[str, Any]]
    passRewardPreviewID: Optional[int] = None
    settleCountdownTime: int
    failSettleCountdownTime: Optional[int] = None
    quitSettleCountdownTime: int
    settleShows: List[str]
    forbiddenRestart: Optional[bool] = None
    settleUIType: Optional[str] = None
    recommendElementTypes: List[str]
    FEOFOGNECFH: List[str]
    levelConfigMap: LevelConfigMap
    enterCostItems: List[int]
    MKCJLIGKICK: int
    cityID: Optional[int] = None
    entryPicPath: str
    stateType: str
    HKGDKECPNEA: str
    PFOLCFNOIGF: str
    avatarLimitType: Optional[int] = None
    isDynamicLevel: Optional[bool] = None
    subType: Optional[str] = None
    serialId: Optional[int] = None
    CEJNGDKNBFP: Optional[bool] = None
    JMLFEDHFPNL: Optional[bool] = None
    firstPassRewardPreviewID: Optional[int] = None
    passJumpDungeon: Optional[int] = None
    dontShowPushTips: Optional[bool] = None
    playType: Optional[str] = None
    eventInterval: Optional[int] = None
    reviveIntervalTime: Optional[int] = None
    statueCostID: Optional[int] = None
    statueCostCount: Optional[int] = None
    statueDrop: Optional[int] = None
    IHKGGJBNLIG: Optional[bool] = None
    CADCHBEJFLN: Optional[bool] = None


class DungeonExcelConfigData(BaseModel):
    __root__: List[DungeonExcelConfigDatum]
