# generated by datamodel-codegen:
#   filename:  EmbeddedTextMapConfigData.json
#   timestamp: 2022-11-01T03:56:01+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class EmbeddedTextMapConfigDatum(BaseModel):
    textMapId: str
    textMapContentTextMapHash: int


class EmbeddedTextMapConfigData(BaseModel):
    __root__: List[EmbeddedTextMapConfigDatum]
