# generated by datamodel-codegen:
#   filename:  EmojiSetDataExcelConfigData.json
#   timestamp: 2022-11-01T03:56:02+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class EmojiSetDataExcelConfigDatum(BaseModel):
    id: int
    order: int
    icon: str


class EmojiSetDataExcelConfigData(BaseModel):
    __root__: List[EmojiSetDataExcelConfigDatum]
