# generated by datamodel-codegen:
#   filename:  FettersExcelConfigData.json
#   timestamp: 2022-11-01T03:56:06+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class OpenCond(BaseModel):
    condType: Optional[str] = None
    paramList: List[int]


class FettersExcelConfigDatum(BaseModel):
    MEHNNNCLHLI: int
    OALKEOBGAHC: List[int]
    finishConds: List[int]
    tips: List[int]
    voiceTitleTextMapHash: int
    voiceFile: str
    voiceFileTextTextMapHash: int
    voiceTitleLockedTextMapHash: int
    fetterId: int
    avatarId: int
    openConds: List[OpenCond]
    KIENFJBHKEP: List
    isHiden: Optional[bool] = None


class FettersExcelConfigData(BaseModel):
    __root__: List[FettersExcelConfigDatum]
