# generated by datamodel-codegen:
#   filename:  FetterStoryExcelConfigData.json
#   timestamp: 2022-11-01T03:56:06+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class OpenCond(BaseModel):
    paramList: List[int]
    condType: Optional[str] = None


class KIENFJBHKEPItem(BaseModel):
    condType: str
    paramList: List[int]


class FetterStoryExcelConfigDatum(BaseModel):
    storyTitleTextMapHash: int
    storyContextTextMapHash: int
    storyTitle2TextMapHash: int
    storyContext2TextMapHash: int
    tips: List[int]
    storyTitleLockedTextMapHash: int
    fetterId: int
    avatarId: int
    openConds: List[OpenCond]
    KIENFJBHKEP: List[KIENFJBHKEPItem]


class FetterStoryExcelConfigData(BaseModel):
    __root__: List[FetterStoryExcelConfigDatum]
