# generated by datamodel-codegen:
#   filename:  ForgeExcelConfigData.json
#   timestamp: 2022-11-01T03:56:07+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class MaterialItem(BaseModel):
    id: Optional[int] = None
    count: Optional[int] = None


class ForgeExcelConfigDatum(BaseModel):
    id: int
    playerLevel: int
    isDefaultShow: Optional[bool] = None
    effectiveWorldLevels: List[int]
    forgeType: int
    showItemId: int
    HAHBBIAFIBE: Optional[int] = None
    resultItemId: Optional[int] = None
    resultItemCount: int
    forgeTime: int
    queueNum: int
    scoinCost: int
    randomItems: List[Dict[str, Any]]
    materialItems: List[MaterialItem]
    priority: int
    forgePoint: Optional[int] = None
    forgePointNoticeTextMapHash: int
    mainRandomDropId: Optional[int] = None


class ForgeExcelConfigData(BaseModel):
    __root__: List[ForgeExcelConfigDatum]
