# generated by datamodel-codegen:
#   filename:  GadgetCurveExcelConfigData.json
#   timestamp: 2022-11-01T03:56:10+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class CurveInfo(BaseModel):
    type: str
    arith: str
    value: float


class GadgetCurveExcelConfigDatum(BaseModel):
    level: int
    curveInfos: List[CurveInfo]


class GadgetCurveExcelConfigData(BaseModel):
    __root__: List[GadgetCurveExcelConfigDatum]
