# generated by datamodel-codegen:
#   filename:  GadgetExcelConfigData.json
#   timestamp: 2022-11-01T03:56:10+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class GadgetExcelConfigDatum(BaseModel):
    type: Optional[str] = None
    jsonName: str
    tags: List[str]
    itemJsonName: str
    inteeIconName: str
    interactNameTextMapHash: int
    id: int
    nameTextMapHash: int
    prefabPathHashSuffix: Optional[int] = None
    prefabPathHashPre: Optional[int] = None
    campID: Optional[int] = None
    LODPatternName: str
    hasMove: Optional[bool] = None
    hasAudio: Optional[bool] = None
    isInteractive: Optional[bool] = None
    visionLevel: Optional[str] = None
    mpPropID: Optional[int] = None
    isEquip: Optional[bool] = None
    itemPrefabPathHashSuffix: Optional[int] = None
    itemPrefabPathHashPre: Optional[int] = None
    landSoundID: Optional[int] = None
    clientScriptHashSuffix: Optional[int] = None
    clientScriptHashPre: Optional[int] = None
    radarHintID: Optional[int] = None
    OENFMDLBKKD: Optional[bool] = None
    BHFAONDJLEA: Optional[int] = None
    prefabPathRemoteHashSuffix: Optional[int] = None
    prefabPathRemoteHashPre: Optional[int] = None
    controllerPathHashSuffix: Optional[int] = None
    controllerPathHashPre: Optional[int] = None


class GadgetExcelConfigData(BaseModel):
    __root__: List[GadgetExcelConfigDatum]
