# generated by datamodel-codegen:
#   filename:  GadgetTitleExcelConfigData.json
#   timestamp: 2022-11-01T03:56:11+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class GadgetTitleExcelConfigDatum(BaseModel):
    gadgetId: int
    titleTextMapHash: int


class GadgetTitleExcelConfigData(BaseModel):
    __root__: List[GadgetTitleExcelConfigDatum]
