# generated by datamodel-codegen:
#   filename:  HandbookQuestGuideExcelConfigData.json
#   timestamp: 2022-11-01T03:56:12+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class JMGHMAJDBAHItem(BaseModel):
    param: List[int]
    type: Optional[str] = None


class HandbookQuestGuideExcelConfigDatum(BaseModel):
    PKKHGMOGBCC: int
    typeID: int
    DFDGNBFLAND: int
    order: int
    icon: str
    JMGHMAJDBAH: List[JMGHMAJDBAHItem]
    OEGLGMFHJJK: Optional[int] = None
    KDMDJJNBJLB: Optional[str] = None
    AMPOMFLLHFE: Optional[bool] = None
    MPJOBAMPMPP: Optional[int] = None
    JGILCDPCAJB: Optional[int] = None


class HandbookQuestGuideExcelConfigData(BaseModel):
    __root__: List[HandbookQuestGuideExcelConfigDatum]
