# generated by datamodel-codegen:
#   filename:  HomeWorldFurnitureExcelConfigData.json
#   timestamp: 2022-11-01T03:56:13+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class HomeWorldFurnitureExcelConfigDatum(BaseModel):
    furnitureGadgetID: List[int]
    furnType: List[int]
    surfaceType: Optional[str] = None
    gridStyle: Optional[int] = None
    comfort: Optional[int] = None
    stackLimit: Optional[int] = None
    cost: Optional[int] = None
    ILELJMLDKJD: Optional[int] = None
    itemIcon: str
    effectIcon: str
    furnitureNameTextMapHash: Optional[float] = None
    rankLevel: int
    jsonName: str
    id: int
    nameTextMapHash: int
    descTextMapHash: int
    icon: str
    itemType: str
    rank: Optional[int] = None
    FEFLOACIIHG: Optional[str] = None
    isUnique: Optional[int] = None
    isSpecialFurniture: Optional[int] = None
    height: Optional[float] = None
    HOPAHNBOFGL: Optional[int] = None
    LNPMOGCFENE: Optional[int] = None
    NEPDEOAKJMK: Optional[int] = None
    OBHGNBCACOO: Optional[int] = None
    roomSceneID: Optional[int] = None
    pushTipsId: Optional[int] = None
    NAIHAJEDPOL: Optional[str] = None
    IDMFBPPJMEN: Optional[bool] = None


class HomeWorldFurnitureExcelConfigData(BaseModel):
    __root__: List[HomeWorldFurnitureExcelConfigDatum]
