# generated by datamodel-codegen:
#   filename:  HomeWorldFurnitureTypeExcelConfigData.json
#   timestamp: 2022-11-01T03:56:13+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class HomeWorldFurnitureTypeExcelConfigDatum(BaseModel):
    typeID: int
    CCEOKJDDNPP: int
    typeNameTextMapHash: int
    typeName2TextMapHash: int
    tabIcon: str
    isShowInBag: Optional[bool] = None
    sceneType: Optional[str] = None
    CDOPFMAHELD: Optional[int] = None


class HomeWorldFurnitureTypeExcelConfigData(BaseModel):
    __root__: List[HomeWorldFurnitureTypeExcelConfigDatum]
