# generated by datamodel-codegen:
#   filename:  LoadingTipsExcelConfigData.json
#   timestamp: 2022-11-01T03:56:14+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class LoadingTipsExcelConfigDatum(BaseModel):
    id: int
    tipsTitleTextMapHash: int
    tipsDescTextMapHash: int
    stageID: str
    startTime: str
    endTime: str
    limitOpenState: str
    preMainQuestIds: str
    OEGMFOHBAHC: List[int]
    NFNEGJEAKBL: List[int]
    GFGPIGCAPFB: List
    weight: Optional[int] = None
    minLevel: Optional[int] = None


class LoadingTipsExcelConfigData(BaseModel):
    __root__: List[LoadingTipsExcelConfigDatum]
