# generated by datamodel-codegen:
#   filename:  LocalizationExcelConfigData.json
#   timestamp: 2022-11-01T03:56:15+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class LocalizationExcelConfigDatum(BaseModel):
    id: int
    assetType: str
    defaultPath: str
    scPath: str
    tcPath: str
    enPath: str
    krPath: str
    jpPath: str
    esPath: str
    frPath: str
    idPath: str
    ptPath: str
    ruPath: str
    thPath: str
    viPath: str
    dePath: str
    DKPALIBPOLC: str
    DIOGOEKBEDI: str


class LocalizationExcelConfigData(BaseModel):
    __root__: List[LocalizationExcelConfigDatum]
