# generated by datamodel-codegen:
#   filename:  MailExcelConfigData.json
#   timestamp: 2022-11-01T03:56:15+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class MailExcelConfigDatum(BaseModel):
    id: int
    expireDays: int
    titleTextMapHash: int
    contentTextMapHash: int
    senderTextMapHash: int
    isStar: Optional[bool] = None
    rewardId: Optional[int] = None


class MailExcelConfigData(BaseModel):
    __root__: List[MailExcelConfigDatum]
