# generated by datamodel-codegen:
#   filename:  MonsterExcelConfigData.json
#   timestamp: 2022-11-01T03:56:22+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class HpDrop(BaseModel):
    dropId: Optional[int] = None
    hpPercent: Optional[float] = None


class PropGrowCurve(BaseModel):
    type: Optional[str] = None
    growCurve: Optional[str] = None


class MonsterExcelConfigDatum(BaseModel):
    monsterName: str
    type: str
    scriptDataPathHashSuffix: Optional[int] = None
    scriptDataPathHashPre: Optional[int] = None
    serverScript: str
    combatConfigHashSuffix: int
    combatConfigHashPre: int
    affix: List[int]
    ai: str
    isAIHashCheck: Optional[bool] = None
    equips: List[int]
    hpDrops: List[HpDrop]
    killDropId: Optional[int] = None
    excludeWeathers: str
    featureTagGroupID: Optional[int] = None
    mpPropID: int
    skin: str
    describeId: Optional[int] = None
    combatBGMLevel: Optional[int] = None
    entityBudgetLevel: Optional[int] = None
    hpBase: float
    attackBase: Optional[float] = None
    defenseBase: Optional[float] = None
    fireSubHurt: Optional[float] = None
    grassSubHurt: Optional[float] = None
    waterSubHurt: Optional[float] = None
    elecSubHurt: Optional[float] = None
    windSubHurt: Optional[float] = None
    iceSubHurt: Optional[float] = None
    rockSubHurt: Optional[float] = None
    propGrowCurves: List[PropGrowCurve]
    physicalSubHurt: Optional[float] = None
    prefabPathRagdollHashSuffix: int
    prefabPathRagdollHashPre: int
    animatorConfigPathHashSuffix: Optional[int] = None
    NJIEKKLKLLD: Optional[int] = None
    id: int
    nameTextMapHash: int
    prefabPathHashSuffix: int
    prefabPathHashPre: int
    prefabPathRemoteHashSuffix: int
    prefabPathRemoteHashPre: int
    controllerPathHashSuffix: int
    controllerPathHashPre: int
    controllerPathRemoteHashSuffix: int
    controllerPathRemoteHashPre: int
    campID: int
    LODPatternName: str
    securityLevel: Optional[str] = None
    isInvisibleReset: Optional[bool] = None
    safetyCheck: Optional[bool] = None
    isSceneReward: Optional[bool] = None
    visionLevel: Optional[str] = None
    radarHintID: Optional[int] = None


class MonsterExcelConfigData(BaseModel):
    __root__: List[MonsterExcelConfigDatum]
