# generated by datamodel-codegen:
#   filename:  MonsterSpecialNameExcelConfigData.json
#   timestamp: 2022-11-01T03:56:23+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class MonsterSpecialNameExcelConfigDatum(BaseModel):
    specialNameID: int
    specialNameLabID: int
    specialNameTextMapHash: int
    isInRandomList: Optional[bool] = None


class MonsterSpecialNameExcelConfigData(BaseModel):
    __root__: List[MonsterSpecialNameExcelConfigDatum]
