# generated by datamodel-codegen:
#   filename:  MonsterRelationshipExcelConfigData.json
#   timestamp: 2022-11-01T03:56:23+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class MonsterRelationshipExcelConfigDatum(BaseModel):
    id: int
    tagStr: str
    monsterRarity: str
    BLGCIFIJPPI: str
    JDPJINJEANM: Optional[bool] = None


class MonsterRelationshipExcelConfigData(BaseModel):
    __root__: List[MonsterRelationshipExcelConfigDatum]
