# generated by datamodel-codegen:
#   filename:  MonsterTitleExcelConfigData.json
#   timestamp: 2022-11-01T03:56:24+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class MonsterTitleExcelConfigDatum(BaseModel):
    titleID: int
    titleNameTextMapHash: int
    isInverted: Optional[bool] = None


class MonsterTitleExcelConfigData(BaseModel):
    __root__: List[MonsterTitleExcelConfigDatum]
