# generated by datamodel-codegen:
#   filename:  MonsterCurveExcelConfigData.json
#   timestamp: 2022-11-01T03:56:20+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class CurveInfo(BaseModel):
    type: str
    arith: str
    value: Optional[float] = None


class MonsterCurveExcelConfigDatum(BaseModel):
    level: int
    curveInfos: List[CurveInfo]


class MonsterCurveExcelConfigData(BaseModel):
    __root__: List[MonsterCurveExcelConfigDatum]
