# generated by datamodel-codegen:
#   filename:  MonsterDescribeExcelConfigData.json
#   timestamp: 2022-11-01T03:56:21+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class MonsterDescribeExcelConfigDatum(BaseModel):
    id: int
    nameTextMapHash: int
    titleID: int
    specialNameLabID: int
    icon: str


class MonsterDescribeExcelConfigData(BaseModel):
    __root__: List[MonsterDescribeExcelConfigDatum]
