# generated by datamodel-codegen:
#   filename:  NpcExcelConfigData.json
#   timestamp: 2022-11-01T03:56:26+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class NpcExcelConfigDatum(BaseModel):
    jsonName: str
    alias: str
    scriptDataPath: str
    luaDataPath: str
    dyePart: str
    billboardIcon: str
    templateEmotionPath: str
    MEGNJOPONPJ: List[int]
    PAAANBHPCNL: int
    id: int
    nameTextMapHash: int
    prefabPathHashSuffix: int
    prefabPathHashPre: int
    campID: int
    LODPatternName: str
    hasMove: Optional[bool] = None
    hasAudio: Optional[bool] = None
    jsonPathHashSuffix: Optional[int] = None
    jsonPathHashPre: Optional[int] = None
    isDaily: Optional[bool] = None
    gachaCardNameHashSuffix: Optional[int] = None
    coopPicNameHashSuffix: Optional[int] = None
    invisiable: Optional[bool] = None
    disableShowName: Optional[bool] = None
    bodyType: Optional[str] = None
    firstMetId: Optional[int] = None
    KDOFFPNPJFD: Optional[bool] = None
    billboardType: Optional[str] = None
    animatorConfigPathHashSuffix: Optional[int] = None
    NJIEKKLKLLD: Optional[int] = None
    luaDataIndex: Optional[int] = None
    animatorConfigPathHashPre: Optional[bool] = None
    BEHJMAEBDNO: Optional[bool] = None
    FJMJMIGMJCL: Optional[str] = None


class NpcExcelConfigData(BaseModel):
    __root__: List[NpcExcelConfigDatum]
