# generated by datamodel-codegen:
#   filename:  NpcFirstMetExcelConfigData.json
#   timestamp: 2022-11-01T03:56:27+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class NpcFirstMetExcelConfigDatum(BaseModel):
    id: int
    subQuestIdList: List[int]
    avatarID: int
    avatarDescriptionTextMapHash: int


class NpcFirstMetExcelConfigData(BaseModel):
    __root__: List[NpcFirstMetExcelConfigDatum]
