# generated by datamodel-codegen:
#   filename:  OptionExcelConfigData.json
#   timestamp: 2022-11-01T03:56:28+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class OptionExcelConfigDatum(BaseModel):
    id: int
    contentTextMapHash: int
    inteeIconName: str
    gusetInteeButtonShow: Optional[bool] = None
    CBPOAHNPDGM: Optional[float] = None
    cancelOnlineMatch: Optional[bool] = None


class OptionExcelConfigData(BaseModel):
    __root__: List[OptionExcelConfigDatum]
