# generated by datamodel-codegen:
#   filename:  PersonalLineExcelConfigData.json
#   timestamp: 2022-11-01T03:56:29+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class PersonalLineExcelConfigDatum(BaseModel):
    id: int
    titleTextMapHash: int
    chapterId: int
    startQuestId: int
    avatarId: int
    preQuestId: List[int]
    startTime: str
    descTextMapHash: int
    sortOrder: int


class PersonalLineExcelConfigData(BaseModel):
    __root__: List[PersonalLineExcelConfigDatum]
