# generated by datamodel-codegen:
#   filename:  PlayerLevelExcelConfigData.json
#   timestamp: 2022-11-01T03:56:30+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class PlayerLevelExcelConfigDatum(BaseModel):
    level: int
    exp: Optional[int] = None
    unlockDescTextMapHash: int
    rewardId: Optional[int] = None
    unlockWorldLevel: Optional[int] = None
    expeditionLimitAdd: Optional[int] = None


class PlayerLevelExcelConfigData(BaseModel):
    __root__: List[PlayerLevelExcelConfigDatum]
