# generated by datamodel-codegen:
#   filename:  PushTipsConfigData.json
#   timestamp: 2022-11-01T03:56:30+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class PushTipsConfigDatum(BaseModel):
    pushTipsId: int
    rewardId: Optional[int] = None
    titleTextMapHash: int
    subtitleTextMapHash: int
    pushTipsType: str
    showIcon: str
    tabIcon: str
    tutorialId: int
    codexType: Optional[str] = None
    showImmediately: Optional[bool] = None
    groupId: Optional[int] = None
    EKGJEGIPLCA: Optional[bool] = None


class PushTipsConfigData(BaseModel):
    __root__: List[PushTipsConfigDatum]
