# generated by datamodel-codegen:
#   filename:  ReliquaryExcelConfigData.json
#   timestamp: 2022-11-01T03:56:38+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class ReliquaryExcelConfigDatum(BaseModel):
    equipType: str
    showPic: str
    rankLevel: int
    mainPropDepotId: int
    appendPropDepotId: int
    addPropLevels: List[int]
    baseConvExp: int
    maxLevel: int
    destroyReturnMaterial: List[int]
    destroyReturnMaterialCount: List[int]
    id: int
    nameTextMapHash: int
    descTextMapHash: int
    icon: str
    itemType: str
    weight: int
    rank: int
    gadgetId: int
    appendPropNum: Optional[int] = None
    setId: Optional[int] = None
    storyId: Optional[int] = None
    destroyRule: Optional[str] = None
    dropable: Optional[bool] = None


class ReliquaryExcelConfigData(BaseModel):
    __root__: List[ReliquaryExcelConfigDatum]
