# generated by datamodel-codegen:
#   filename:  ReliquarySetExcelConfigData.json
#   timestamp: 2022-11-01T03:56:40+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class ReliquarySetExcelConfigDatum(BaseModel):
    setId: int
    setIcon: str
    setNeedNum: List[int]
    EquipAffixId: Optional[int] = None
    containsList: List[int]
    FDKHPHNGCBL: Optional[int] = None
    JCLGCACJMMK: List[int]
    textList: List[int]
    DisableFilter: Optional[int] = None


class ReliquarySetExcelConfigData(BaseModel):
    __root__: List[ReliquarySetExcelConfigDatum]
