# generated by datamodel-codegen:
#   filename:  ReliquaryAffixExcelConfigData.json
#   timestamp: 2022-11-01T03:56:36+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class ReliquaryAffixExcelConfigDatum(BaseModel):
    id: int
    depotId: int
    groupId: int
    propType: str
    propValue: float


class ReliquaryAffixExcelConfigData(BaseModel):
    __root__: List[ReliquaryAffixExcelConfigDatum]
