# generated by datamodel-codegen:
#   filename:  ReliquaryLevelExcelConfigData.json
#   timestamp: 2022-11-01T03:56:39+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class AddProp(BaseModel):
    propType: str
    value: float


class ReliquaryLevelExcelConfigDatum(BaseModel):
    level: int
    addProps: List[AddProp]
    rank: Optional[int] = None
    exp: Optional[int] = None


class ReliquaryLevelExcelConfigData(BaseModel):
    __root__: List[ReliquaryLevelExcelConfigDatum]
