# generated by datamodel-codegen:
#   filename:  ReliquaryMainPropExcelConfigData.json
#   timestamp: 2022-11-01T03:56:40+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class ReliquaryMainPropExcelConfigDatum(BaseModel):
    id: int
    propDepotId: int
    propType: str
    affixName: str


class ReliquaryMainPropExcelConfigData(BaseModel):
    __root__: List[ReliquaryMainPropExcelConfigDatum]
