# generated by datamodel-codegen:
#   filename:  ReputationCityExcelConfigData.json
#   timestamp: 2022-11-01T03:56:44+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class ReputationCityExcelConfigDatum(BaseModel):
    cityId: int
    exploreAreaVec: List[int]
    virtualItemId: int
    openState: str
    bgIconPath: str
    bgEffectPath: str
    explainTitleTextMapHash: int
    descTextMapHash: int
    rewardItemId: int
    rewardItemDescTextMapHash: int
    rewardItemIcon: str
    rewardBgIcon: str
    cityIcon: str


class ReputationCityExcelConfigData(BaseModel):
    __root__: List[ReputationCityExcelConfigDatum]
