# generated by datamodel-codegen:
#   filename:  ReputationLevelExcelConfigData.json
#   timestamp: 2022-11-01T03:56:44+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class ReputationLevelExcelConfigDatum(BaseModel):
    id: int
    level: int
    cityId: int
    levelNameTextMapHash: int
    nextLevelExp: Optional[int] = None
    rewardId: int
    requestGroupId: int
    requestNum: int
    requestAcceptNum: int
    functionId: Optional[int] = None


class ReputationLevelExcelConfigData(BaseModel):
    __root__: List[ReputationLevelExcelConfigDatum]
