# generated by datamodel-codegen:
#   filename:  SceneExcelConfigData.json
#   timestamp: 2022-11-01T03:56:45+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class SceneExcelConfigDatum(BaseModel):
    id: int
    type: str
    scriptData: str
    overrideDefaultProfile: str
    levelEntityConfig: str
    specifiedAvatarList: List[int]
    comment: str
    HLKDAIPGHGO: List[int]
    LJNMKKCMLOL: Optional[bool] = None
    maxSpecifiedAvatarNum: Optional[int] = None
    FEICPPHODGE: Optional[str] = None
    LIIICMJEHLG: Optional[bool] = None
    LLBGGMJAGIE: Optional[int] = None
    ILGKOJFHOKJ: Optional[bool] = None
    KKPHDMLHKOL: Optional[bool] = None
    BDDELKPADBA: Optional[float] = None
    KHNIPCAPJFJ: Optional[str] = None
    entityAppearSorted: Optional[int] = None
    DCLGPLMLLIP: Optional[str] = None


class SceneExcelConfigData(BaseModel):
    __root__: List[SceneExcelConfigDatum]
