# generated by datamodel-codegen:
#   filename:  TowerBuffExcelConfigData.json
#   timestamp: 2022-11-01T03:56:46+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class TowerBuffExcelConfigDatum(BaseModel):
    towerBuffId: int
    lastingType: str
    descTextMapHash: int
    buffIcon: str
    buffId: int


class TowerBuffExcelConfigData(BaseModel):
    __root__: List[TowerBuffExcelConfigDatum]
