# generated by datamodel-codegen:
#   filename:  WeaponCodexExcelConfigData.json
#   timestamp: 2022-11-01T03:56:46+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class WeaponCodexExcelConfigDatum(BaseModel):
    Id: int
    weaponId: int
    SortOrder: int
    isDisuse: Optional[bool] = None
    showOnlyUnlocked: Optional[bool] = None


class WeaponCodexExcelConfigData(BaseModel):
    __root__: List[WeaponCodexExcelConfigDatum]
