# generated by datamodel-codegen:
#   filename:  WeaponCurveExcelConfigData.json
#   timestamp: 2022-11-01T03:56:47+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class CurveInfo(BaseModel):
    type: str
    arith: str
    value: float


class WeaponCurveExcelConfigDatum(BaseModel):
    level: int
    curveInfos: List[CurveInfo]


class WeaponCurveExcelConfigData(BaseModel):
    __root__: List[WeaponCurveExcelConfigDatum]
