# generated by datamodel-codegen:
#   filename:  WeaponExcelConfigData.json
#   timestamp: 2022-11-01T03:56:48+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class WeaponPropItem(BaseModel):
    propType: Optional[str] = None
    initValue: Optional[float] = None
    type: str


class WeaponExcelConfigDatum(BaseModel):
    weaponType: str
    rankLevel: int
    weaponBaseExp: int
    skillAffix: List[int]
    weaponProp: List[WeaponPropItem]
    awakenTexture: str
    awakenLightMapTexture: str
    awakenIcon: str
    weaponPromoteId: int
    storyId: Optional[int] = None
    awakenCosts: List[int]
    MJGNGJHBAGI: int
    gachaCardNameHashPre: int
    destroyRule: Optional[str] = None
    destroyReturnMaterial: List[int]
    destroyReturnMaterialCount: List[int]
    id: int
    nameTextMapHash: int
    descTextMapHash: int
    icon: str
    itemType: str
    weight: int
    rank: int
    gadgetId: int
    initialLockState: Optional[int] = None
    awakenMaterial: Optional[int] = None
    enhanceRule: Optional[int] = None
    unRotate: Optional[bool] = None


class WeaponExcelConfigData(BaseModel):
    __root__: List[WeaponExcelConfigDatum]
