# generated by datamodel-codegen:
#   filename:  WeaponLevelExcelConfigData.json
#   timestamp: 2022-11-01T03:56:48+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class WeaponLevelExcelConfigDatum(BaseModel):
    level: int
    requiredExps: List[int]


class WeaponLevelExcelConfigData(BaseModel):
    __root__: List[WeaponLevelExcelConfigDatum]
